/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 *
 * MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */
/*
 * File name:  RfxStatusDef.h
 * Author: Jun Liu (MTK80064)
 * Description:
 *  Define the keys of shared status.
 */

#include "RfxDefs.h"
#include "RfxStatusDefs.h"
#include "RfxVariant.h"
#include "RfxDefaultValueTable.h"

StatusDefaultValueEntry s_default_value_table[] = {
    /*Please add your default value below this line*/
    /*NOTE. below every line should be ended by "" */
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CARD_TYPE, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CDMA_CARD_TYPE, RfxVariant(4)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CDMA_CARD_READY, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CDMA_FILE_READY, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CDMA3G_DUALMODE_CARD, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_ESIMIND_APPLIST, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CDMA_LOCKED_CARD, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_UICC_SUB_CHANGED_STATUS, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_UICC_GSM_NUMERIC, RfxVariant(String8(""))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_UICC_CDMA_NUMERIC, RfxVariant(String8(""))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_C2K_IMSI, RfxVariant(String8(""))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IS_EUICC_CARD, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_ECGLA_CAPABILITY, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SIM_EID, RfxVariant(String8(""))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_UICC_RESET_APPLICATION, RfxVariant(String8(""))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_BTSAP_STATUS, RfxVariant(BT_SAP_INIT)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_BTSAP_CURRENT_PROTOCOL, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_BTSAP_SUPPORT_PROTOCOL, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_BTSAP_ATR, RfxVariant(String8(""))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SIM_ESIMS_CAUSE, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_ECPIN_STATE, RfxVariant(RFX_ECPIN_DONE)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_MODEM_SIM_TASK_READY, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SERVICE_STATE, RfxVariant(RfxNwServiceState())),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SIGNAL_STRENGTH, RfxVariant(String8(""))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_VOICE_TYPE, RfxVariant()),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_DATA_TYPE, RfxVariant()),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_RADIO_STATE, RfxVariant()),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_MODEM_POWER_OFF, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_MODEM_OFF_STATE, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SIM_STATE, RfxVariant(RFX_SIM_STATE_NOT_READY)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SIM_INSERT_STATE, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_GSM_IMSI, RfxVariant(String8(""))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SLOT_CAPABILITY, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_OTA_STATUS, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CALL_STATE, RfxVariant(RfxCallState())),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_VOICE_CALL_COUNT, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_AP_VOICE_CALL_COUNT, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_EMERGENCY_MODE, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_EMERGENCY_CALLBACK_MODE, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CARRIER_AUTO_APPROVE_INCOMING, RfxVariant(String8("true"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_EMERGENCY_MODE_IN_FLIGHT_MODE, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_ATCI_IS_NUMERIC, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CALL_EXIST, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_DATA_CONNECTION, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_WORLD_MODE_STATE, RfxVariant(1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_GSM_WORLD_MODE_STATE, RfxVariant(1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CDMA_WORLD_MODE_STATE, RfxVariant(1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_WORLD_MODE_BLOCKED_STATE, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_WORLD_MODE_BLOCKED_CHANGING_STATE, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CELLULAR_PS_STATE, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_WFC_STATE, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_WFC_LOCK_STATE, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_MAIN_CAPABILITY_SLOT, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_DEFAULT_DATA_SIM, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_PREFERRED_DATA_SIM, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_ECC_PREFERRED_RAT, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CALL_DISCONNECTED, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IS_GWSD_ACTION_ONGOING, RfxVariant(false)),/* GWSD */
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CC_FAKE_MODE, RfxVariant(0)),/* GWSD */
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CC_FAKE_MODE, RfxVariant(false)),/* GWSD */
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SLOT_FIXED_CAPABILITY, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_RADIO_POWER_MSIM_MODE, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_REQUEST_RADIO_POWER, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_REQUEST_MODEM_POWER, RfxVariant(true)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_RADIO_LOCK, RfxVariant(RADIO_LOCK_IDLE)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_GCF_TEST_MODE, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_GSM_INBOUND_SMS_TYPE, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_GSM_INBOUND_SMS_TXID, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SMS_FW_READY, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SMS_PHONE_STORAGE, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CDMA_INBOUND_SMS_TYPE, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CDMA_INBOUND_SMS_TXID, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CDMA_INBOUND_SMS_PRE_TXID, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CDMA_SMS_REPLY_SEQ_NO, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CDMA_SMS_ADDR, RfxVariant(Vector<char>())),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CDMA_MO_SMS_STATE, RfxVariant(1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CDMA_PENDING_VMI, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_PREFERRED_NW_TYPE, RfxVariant(RfxVariant(-1))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_NR_SWITCH_SLOT, RfxVariant(RfxVariant(0))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IS_NR_SWITCHING, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IS_RAT_MODE_SWITCHING, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_NWS_MODE, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_OPERATOR, RfxVariant(String8(""))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_OPERATOR_INCLUDE_LIMITED, RfxVariant(String8(""))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_MODESWITCH_FINISHED, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CDMA3G_SWITCH_CARD, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CAPABILITY_SWITCH_STATE, RfxVariant(CAPABILITY_SWITCH_STATE_IDLE)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CAPABILITY_SWITCH_WAIT_MODULE, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SIM_SWITCH_RADIO_UNAVAIL_TIME, RfxVariant(int64_t(0))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IS_CAT_RUNNING, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_STK_CACHE_CMD_TYPE, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_STK_CMD_ID, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CAPABILITY_SWITCH_URC_CHANNEL, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_PCO_STATUS, RfxVariant(String8(""))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_HAD_POWER_OFF_MD, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_TRN_CALLID, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_TRN, RfxVariant(String8(""))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_DSBP_ENHANCEMENT_STATE, RfxVariant(DSBP_ENHANCEMENT_END)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CAPABILITY_SWITCH_KEEP_EBOOT, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CDMA_SPN, RfxVariant(String8(""))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_GSM_SPN, RfxVariant(String8(""))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_GSM_GID1, RfxVariant(String8(""))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SLOT_ALLOW, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_GSM_PNN, RfxVariant(String8(""))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_GSM_IMPI, RfxVariant(String8(""))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_GSM_CACHE_FCP, RfxVariant(String8(""))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_GSM_CACHE_BINARY, RfxVariant(String8(""))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_MD_ICCID_SUPPORT, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SIM_ICCID, RfxVariant(String8(""))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SIM_ONOFF_STATE, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SIM_ONOFF_SWITCHING_STATE, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SIM_ONOFF_ENABLED, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_MODEM_SIMONOFF_SUPPORT, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_AOSP_UICC_APPLICATIONS_ENABLE_RESPONSE_STATE, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_AOSP_UICC_APPLICATIONS_ENABLE_STATE, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SIM_POWER_STATE, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_AP_SIM_SWITCH_MODE, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_MD_SIM_SWITCH_MODE, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_CONNECTION_STATE, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CALL_LIST, RfxVariant(Vector<RfxImsCallInfo*>())),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_RESTORE_IMS_CONFERENCE_PARTICIPANT, RfxVariant(String8("true"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_OPERATE_IMS_CONFERENCE_PARTICIPANTS_BY_USER_ENTITY,
            RfxVariant(String8("true"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_SPECIFIC_CONFERENCE_MODE, RfxVariant(String8("0"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CALL_OCUPPY_RF, RfxVariant(true)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_XUI_INFO, RfxVariant(Vector<String8>())),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_HIGH_PRIORITY_CLIR_PREFIX_SUPPORTED, RfxVariant(String8("false"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CONFIG_DEVICE_VOLTE_AVAILABLE, RfxVariant(String8("0"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CONFIG_DEVICE_VT_AVAILABLE, RfxVariant(String8("0"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CONFIG_DEVICE_WFC_AVAILABLE, RfxVariant(String8("0"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CONFIG_DEVICE_VONR_AVAILABLE, RfxVariant(String8("0"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CONFIG_DEVICE_VINR_AVAILABLE, RfxVariant(String8("0"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CONFIG_DEVICE_5G_VOWIFI_AVAILABLE, RfxVariant(String8("0"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CARRIER_ALLOW_TURN_OFF_IMS, RfxVariant(String8("1"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_VOLTE_STATE, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SCREEN_STATE, RfxVariant(1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_TEMP_DATA_SWTICH, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IN_CALL, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_HANGUP_FLIP, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CUSTOMIZED_USER_AGENT_FORMAT, RfxVariant(String8("0"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SML_SLOT_LOCK_POLICY, RfxVariant(0)), \
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SML_SLOT_LOCK_POLICY_LOCK_STATE, RfxVariant(1)), \
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SML_SLOT_LOCK_POLICY_SERVICE_CAPABILITY, RfxVariant(0)), \
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SML_SLOT_LOCK_POLICY_VALID_CARD, RfxVariant(0)), \
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_PDN_ACT_AID, RfxVariant(RFX_NO_ONGOING_IMS_PDN_AID)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_PDN_DEACT_AID, RfxVariant(RFX_NO_ONGOING_IMS_PDN_AID)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_EIMS_PDN_ACT_AID, RfxVariant(RFX_NO_ONGOING_IMS_PDN_AID)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_EIMS_PDN_DEACT_AID, RfxVariant(RFX_NO_ONGOING_IMS_PDN_AID)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SML_SLOT_LOCK_CONFIG_CHECKED, RfxVariant(false)), \
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SML_SLOT_LOCK_MD_SUPPORTED, RfxVariant(false)), \
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_MODEM_RESET,RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SMS_FORMAT_CHANGE_ONGOING, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_GWSD_MODE, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_REGISTRATION_STATE, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_REGISTRATION_RAT, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_EMERGENCY_BEARER_SUPPORT, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_VOPS, RfxVariant(-1)), /* VOPS indication */
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_EMERGENCY_SUPPORT_STATE, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_NETWORK_SCAN_ONGOING, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_DSDA_MODE, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_INCOMING_CALL_RULE, RfxVariant(String8("0"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CARRIER_IGNORE_CLIR_WHEN_ECC, RfxVariant(String8("1"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_REG_IND_TYPE, RfxVariant(-1)), \
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_REG_IND_ACCOUNT_ID, RfxVariant(-1)), \
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_REG_IND_EXPIRE_TIME, RfxVariant(-1)), \
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_REG_IND_URI, RfxVariant(String8(""))), \
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_REG_IND_ERROR_CODE, RfxVariant(0)), \
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_REG_IND_ERROR_MSG, RfxVariant(String8(""))), \
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_PDN_STATE, RfxVariant(IMS_OR_EIMS_PDN_INIT)), \
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_EIMS_PDN_STATE, RfxVariant(IMS_OR_EIMS_PDN_INIT)), \
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_USSD_SESSION_ONGOING, RfxVariant(false)), \
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFERENCE_FIRST_PARTICIPANT_AS_HOST,
            RfxVariant(String8("false"))),\
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CDMA_CALL_DISCONNECTED, RfxVariant(false)),\
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_MCCMNC_CHANGED, RfxVariant(String8(""))), \
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_RADIO_POWER_ON_FOR_ECC, RfxVariant(false)),\
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_BSP_EMERGENCY_SELECTED_SLOT, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CARRIER_UPDATE_ADDRESS_FROM_ECPI,
            RfxVariant(String8("false"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CARRIER_UPDATE_ADDRESS_BY_PAU_FOR_MO,
            RfxVariant(String8("false"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CARRIER_UPDATE_ADDRESS_BY_SIP_FIELD,
            RfxVariant(String8("true"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CARRIER_TREAT_DUPLICATED_NUMBER_AS_ONE_PARTICIPANT,
            RfxVariant(String8("true"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_DATA_CONNECTION_EXP_IMS, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_UNSOLICITED_RESPONSE_FILTER_CHANGED, RfxVariant(127)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_AUTO_ANSWER, RfxVariant(String8(""))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_VOLTE_EMC_SUPPORTED, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_VONR_EMC_SUPPORTED, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_VONR_EMF_SUPPORTED, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CARRIER_IGNORE_SMS_FOR_EIMS, RfxVariant(String8("0"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_LTE_RRC_STATE, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SIM_INIT_STATUS, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_CARRIER_VIWIFI_INDEPENDENT_VOWIFI,
            RfxVariant(String8("0"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IGNORE_VOLTE_VILTE_FOR_23G, RfxVariant(String8("false"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_ESIPCPI_REASON, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_ONS, RfxVariant(String8(""))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SHORT_ONS, RfxVariant(String8(""))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SBP_ID, RfxVariant(String8("0"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SBP_SUB_ID, RfxVariant(String8("0"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_RILD_INIT_HANDLER_DONE, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_MEP_VERSION, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_MTK_RADIO_CONNECTION_STATE, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IS_CHLD2_ONGOING, RfxVariant(false)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_KEEP_DEFAULT_PDN_FOR_NDDS, RfxVariant(String8("0"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_VOCODER_AMRMODESET, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_VOCODER_AMRWBMODESET,RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_SIP_SESSION_TIMER, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_MIN_SE, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_CANCELLATION_TIMER, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_TDELAY, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_SILENT_REDIAL_ENABLE, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_SIP_T1_TIMER, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_SIP_T2_TIMER, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_SIP_TF_TIMER, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_VLT_SETTING_ENABLED, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_LVC_SETTING_ENABLED, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_DOMAIN_NAME, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_SMS_FORMAT, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_SMS_OVER_IP, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_PUBLISH_TIMER, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_PUBLISH_TIMER_EXTENDED, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_CAPABILITY_DISCOVERY_ENABLED, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_CAPABILITIES_CACHE_EXPIRATION, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_AVAILABILITY_CACHE_EXPIRATION, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_CAPABILITIES_POLL_INTERVAL, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_SOURCE_THROTTLE_PUBLISH, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_MAX_NUMENTRIES_IN_RCL, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_CAPAB_POLL_LIST_SUB_EXP, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_GZIP_FLAG, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_EAB_SETTING_ENABLED, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_VOICE_OVER_WIFI_ROAMING, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_VOICE_OVER_WIFI_MODE, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_VOICE_OVER_WIFI_SETTING_ENABLED, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_RTT_SETTING_ENABLED, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_EPDG_ADDRESS, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_PUBLISH_ERROR_RETRY_TIMER, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_VOICE_OVER_WIFI_MDN, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_VOICE_DOMAIN_PREFERENCE, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_IMS_CONFIG_VONR_SETTING_ENABLED, RfxVariant(String8("n/a"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_PCO_DATA_FEATURE_SUPPORTED, RfxVariant(String8("0"))),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SIM_SWITCH_TYPE_STATE, RfxVariant(0)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_SIM_PHONEBOOK_VERSION, RfxVariant(-1)),
    RFX_STATUS_DEFAULT_VALUE_ENTRY(RFX_STATUS_KEY_LAST_CALL_FAIL_CAUSE, RfxVariant(CALL_FAIL_NORMAL)),
    /*Please add your default value above this line*/
    RFX_STATUS_DEFAULT_VALUE_TABLE_END;
