/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 *
 * MediaTek Inc. (C) 2022. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */
// MTK-START: SIM
{RIL_UNSOL_IMEI_LOCK, mtkRadioExSim::onImeiLock, WAKE_PARTIAL},
{RIL_UNSOL_ICCID_CHANGED, mtkRadioExSim::iccidChangedInd, WAKE_PARTIAL},
{RIL_UNSOL_SIM_TYPE_INFO_IND, mtkRadioExSim::simTypeInfoChangedInd, WAKE_PARTIAL},
{RIL_UNSOL_IMSI_REFRESH_DONE, mtkRadioExSim::onImsiRefreshDone, WAKE_PARTIAL},
{RIL_UNSOL_SIM_POWER_CHANGED, mtkRadioExSim::onSimPowerChangedInd, WAKE_PARTIAL},
{RIL_UNSOL_CARD_DETECTED_IND, mtkRadioExSim::onCardDetectedInd, WAKE_PARTIAL},
// MTK-END
// M: BIP {
{RIL_UNSOL_STK_BIP_PROACTIVE_COMMAND, mtkRadioExSim::bipProactiveCommandInd, WAKE_PARTIAL},
// M: BIP }
// PHB
{RIL_UNSOL_PHB_READY_NOTIFICATION, mtkRadioExSim::phbReadyNotificationInd, WAKE_PARTIAL},
// MTK-START: SIM HOT SWAP
{RIL_UNSOL_SIM_PLUG_IN, mtkRadioExSim::onSimPlugIn, WAKE_PARTIAL},
{RIL_UNSOL_SIM_PLUG_OUT, mtkRadioExSim::onSimPlugOut, WAKE_PARTIAL},
{RIL_UNSOL_SIM_MISSING, mtkRadioExSim::onSimMissing, WAKE_PARTIAL},
{RIL_UNSOL_SIM_RECOVERY, mtkRadioExSim::onSimRecovery, WAKE_PARTIAL},
// MTK-END
// MTK-START: SIM COMMON SLOT
{RIL_UNSOL_TRAY_PLUG_IN, mtkRadioExSim::onSimTrayPlugIn, WAKE_PARTIAL},
{RIL_UNSOL_SIM_COMMON_SLOT_NO_CHANGED, mtkRadioExSim::onSimCommonSlotNoChanged, WAKE_PARTIAL},
// MTK-END
// / M:STK {
{RIL_UNSOL_STK_SETUP_MENU_RESET, mtkRadioExSim::onStkMenuResetInd,  WAKE_PARTIAL},
// / M:STK }
// External SIM [Start]
{RIL_UNSOL_VSIM_OPERATION_INDICATION, mtkRadioExSim::onVsimEventIndication, WAKE_PARTIAL},
{RIL_UNSOL_VIRTUAL_SIM_STATUS_CHANGED, mtkRadioExSim::onVirtualSimStatusChanged, WAKE_PARTIAL},
// External SIM [End]
// MTK-START: SIM SLOT LOCK
{RIL_UNSOL_SIM_SLOT_LOCK_POLICY_NOTIFY, mtkRadioExSim::smlSlotLockInfoChangedInd, WAKE_PARTIAL},
// MTK-END
// MTK-START: SIM ATT RSU
{RIL_UNSOL_ATT_SIM_LOCK_NOTIFICATION, mtkRadioExSim::onRsuSimLockEvent, WAKE_PARTIAL},
{RIL_UNSOL_SML_RSU_EVENT, mtkRadioExSim::onRsuEvent, WAKE_PARTIAL},
// MTK-END
