/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 *
 * MediaTek Inc. (C) 2023. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */
// Vendor data channel solution
{RIL_REQUEST_DCH_BOOTSTRAP_CFG_QRY_CMD_RSP, mtkRadioExDch::dcBootstrapCfgQueryCmdRspCnf},
{RIL_REQUEST_DCH_CREATE_SIP_REQ, mtkRadioExDch::dcCreateSipResponse},
{RIL_REQUEST_DCH_MODIFY_SIP_REQ, mtkRadioExDch::dcModifySipResponse},
{RIL_REQUEST_DCH_CLOSE_SIP_REQ, mtkRadioExDch::dcCloseSipResponse},
{RIL_REQUEST_DCH_CREATE_CMD_RSP, mtkRadioExDch::dcCreateCmdRspCnf},
{RIL_REQUEST_DCH_ENABLE_REQ, mtkRadioExDch::dcEnableRsp},

// MTK data channel solution
{RIL_REQUEST_DCH_ACT_PACKET_ROUTE_REQ, mtkRadioExDch::dchDataActPacketRouteResponse},
{RIL_REQUEST_DCH_IFUP_PACKET_ROUTE_REQ, mtkRadioExDch::dchDataIfupPacketRouteResponse},
{RIL_REQUEST_DCH_DATA_PATH_CONFIG_SYNC_REQ, mtkRadioExDch::dchDataPathConfigSyncResponse},
{RIL_REQUEST_DCH_CREATE_DATA_CHANNEL_REQ, mtkRadioExDch::dchCreateDataChannelResponse},
{RIL_REQUEST_DCH_CLOSE_DATA_CHANNEL_REQ, mtkRadioExDch::dchCloseDataChannelResponse},

