/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 *
 * MediaTek Inc. (C) 2022. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */
{RIL_UNSOL_CALL_RING, radioVoice::callRingInd, WAKE_PARTIAL},
{RIL_UNSOL_RESPONSE_CALL_STATE_CHANGED, radioVoice::callStateChangedInd, WAKE_PARTIAL},
{RIL_UNSOL_CDMA_CALL_WAITING, radioVoice::cdmaCallWaitingInd, WAKE_PARTIAL},
{RIL_UNSOL_CDMA_INFO_REC, radioVoice::cdmaInfoRecInd, WAKE_PARTIAL},
{RIL_UNSOL_CDMA_OTA_PROVISION_STATUS, radioVoice::cdmaOtaProvisionStatusInd, WAKE_PARTIAL},
{RIL_UNSOL_EMERGENCY_NUMBER_LIST, radioVoice::currentEmergencyNumberListInd, WAKE_PARTIAL},
{RIL_UNSOL_ENTER_EMERGENCY_CALLBACK_MODE, radioVoice::enterEmergencyCallbackModeInd, WAKE_PARTIAL},
{RIL_UNSOL_EXIT_EMERGENCY_CALLBACK_MODE, radioVoice::exitEmergencyCallbackModeInd, WAKE_PARTIAL},
{RIL_UNSOL_RINGBACK_TONE, radioVoice::indicateRingbackToneInd, WAKE_PARTIAL},
{RIL_UNSOL_ON_SS, radioVoice::onSupplementaryServiceIndicationInd, WAKE_PARTIAL},
{RIL_UNSOL_RESEND_INCALL_MUTE, radioVoice::resendIncallMuteInd, WAKE_PARTIAL},
{RIL_UNSOL_SRVCC_STATE_NOTIFY, radioVoice::srvccStateNotifyInd, WAKE_PARTIAL},
{RIL_UNSOL_STK_CC_ALPHA_NOTIFY, radioVoice::stkCallControlAlphaNotifyInd, WAKE_PARTIAL},
{RIL_UNSOL_STK_CALL_SETUP, radioVoice::stkCallSetupInd, WAKE_PARTIAL},
{RIL_UNSOL_ON_USSD, radioVoice::onUssdInd, WAKE_PARTIAL},
