/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 *
 * MediaTek Inc. (C) 2022. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */
{RIL_UNSOL_BARRING_INFO, radioNetwork::barringInfoChangedInd, WAKE_PARTIAL},
{RIL_UNSOL_CDMA_PRL_CHANGED, radioNetwork::cdmaPrlChangedInd, WAKE_PARTIAL},
{RIL_UNSOL_CELL_INFO_LIST, radioNetwork::cellInfoListInd, WAKE_PARTIAL},
{RIL_UNSOL_LINK_CAPACITY_ESTIMATE, radioNetwork::currentLinkCapacityEstimate, WAKE_PARTIAL},           // Data
{RIL_UNSOL_PHYSICAL_CHANNEL_CONFIG, radioNetwork::currentPhysicalChannelConfigs, WAKE_PARTIAL},
{RIL_UNSOL_SIGNAL_STRENGTH, radioNetwork::currentSignalStrengthInd, DONT_WAKE},
{RIL_UNSOL_RESPONSE_IMS_NETWORK_STATE_CHANGED, radioNetwork::imsNetworkStateChangedInd, WAKE_PARTIAL},  //IMS
{RIL_UNSOL_NETWORK_SCAN_RESULT, radioNetwork::networkScanResultInd, WAKE_PARTIAL},
{RIL_UNSOL_RESPONSE_VOICE_NETWORK_STATE_CHANGED, radioNetwork::networkStateChangedInd, WAKE_PARTIAL},
{RIL_UNSOL_NITZ_TIME_RECEIVED, radioNetwork::nitzTimeReceivedInd, WAKE_PARTIAL},
{RIL_UNSOL_REGISTRATION_FAILED, radioNetwork::onRegistrationFailedInd, WAKE_PARTIAL},
{RIL_UNSOL_RESTRICTED_STATE_CHANGED, radioNetwork::restrictedStateChangedInd, WAKE_PARTIAL},
{RIL_UNSOL_SUPP_SVC_NOTIFICATION, radioNetwork::suppSvcNotifyInd, WAKE_PARTIAL},                       //SS
{RIL_UNSOL_VOICE_RADIO_TECH_CHANGED, radioNetwork::voiceRadioTechChangedInd, WAKE_PARTIAL},
{RIL_UNSOL_EMERGENCY_NETWORK_SCAN_RESULT, radioNetwork::emergencyNetworkScanResultInd, WAKE_PARTIAL},
{RIL_UNSOL_CELLULAR_IDENTIFIER_DISCLOSED, radioNetwork::cellularIdentifierDisclosedInd, WAKE_PARTIAL},
{RIL_UNSOL_SECURITY_ALGORITHMS_UPDATED, radioNetwork::securityAlgorithmsUpdatedInd, WAKE_PARTIAL},