// SPDX-License-Identifier: MediaTekProprietary
/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */
{RIL_REQUEST_GET_COLP, voidToParcel, parcelToInts, COMMAND_SUPPORETD(1)},
{RIL_REQUEST_SET_COLP, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(1)},
{RIL_REQUEST_GET_COLR, voidToParcel, parcelToInts, COMMAND_SUPPORETD(1)},
{RIL_REQUEST_MODEM_POWEROFF, voidToParcel, parcelToVoid, COMMAND_SUPPORETD(1)},
{RIL_REQUEST_QUERY_PHB_STORAGE_INFO, intsToParcel, parcelToInts, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_WRITE_PHB_ENTRY, phbEntryToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_READ_PHB_ENTRY, intsToParcel, parcelToPhbEntries, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_QUERY_SIM_NETWORK_LOCK, intsToParcel, parcelToInts, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_SET_SIM_NETWORK_LOCK, stringsToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_SET_NETWORK_SELECTION_MANUAL_WITH_ACT, stringsToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_SIM_GET_ICCID,voidToParcel, parcelToString, COMMAND_SUPPORETD(1)},
{RIL_REQUEST_MODEM_POWERON,voidToParcel, parcelToVoid, COMMAND_SUPPORETD(1)},
{RIL_REQUEST_GET_SMS_SIM_MEM_STATUS, voidToParcel, parcelToGetSmsSimMemStatusCnf, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_GET_PHONE_CAPABILITY, voidToParcel, parcelToInts, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_GET_POL_CAPABILITY, voidToParcel, parcelToInts, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_GET_POL_LIST, voidToParcel, parcelToStrings, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_SET_POL_ENTRY, stringsToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_QUERY_UPB_CAPABILITY, voidToParcel, parcelToInts, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_EDIT_UPB_ENTRY, stringsToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_DELETE_UPB_ENTRY, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_READ_UPB_GAS_LIST, intsToParcel, parcelToStrings, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_READ_UPB_GRP, intsToParcel, parcelToInts, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_WRITE_UPB_GRP, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_SET_TRM, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_GET_PHB_STRING_LENGTH, voidToParcel, parcelToInts, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_GET_PHB_MEM_STORAGE, voidToParcel, parcelToGetPhbMemStorage, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_SET_PHB_MEM_STORAGE, stringsToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_READ_PHB_ENTRY_EXT, intsToParcel, parcelToReadPhbEntryExt, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_WRITE_PHB_ENTRY_EXT, writePhbEntryExtToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_GET_SMS_PARAMS, voidToParcel, parcelToSmsParams, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_SET_SMS_PARAMS, smsParamsToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_SIM_GET_ATR, voidToParcel, parcelToString, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_SET_ETWS, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_SET_FD_MODE, fd_ModeToParcel, parcelToInts, COMMAND_SUPPORETD(0)},
/// M: [C2K][IR] Support SVLTE IR feature. @{
{RIL_REQUEST_RESUME_REGISTRATION, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
/// M: [C2K][IR] Support SVLTE IR feature. @}
{RIL_REQUEST_GET_FEMTOCELL_LIST, stringsToParcel, parcelToStrings, COMMAND_SUPPORETD(0)},
// Femtocell (CSG) : abort command shall be sent in differenent channel
{RIL_REQUEST_ABORT_FEMTOCELL_LIST, voidToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_SELECT_FEMTOCELL, stringsToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_ABORT_QUERY_AVAILABLE_NETWORKS , voidToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_HANGUP_ALL, voidToParcel, parcelToVoid, COMMAND_SUPPORETD(1)},
{RIL_REQUEST_FORCE_RELEASE_CALL, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(1)},
{RIL_REQUEST_SET_CALL_INDICATION, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(1)},
{RIL_REQUEST_EMERGENCY_DIAL, dialToParcel, parcelToVoid, COMMAND_SUPPORETD(1)},
//Todo{RIL_REQUEST_SET_ECC_SERVICE_CATEGORY, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(1)},
{RIL_REQUEST_SET_ECC_LIST, stringsToParcel, parcelToVoid, COMMAND_SUPPORETD(1)},
{RIL_REQUEST_GENERAL_SIM_AUTH, simAuthToParcel, parcelToSIM_IO, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_SET_IMS_ENABLE, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(1)},
{RIL_REQUEST_QUERY_AVAILABLE_NETWORKS_WITH_ACT , voidToParcel, parcelToStrings, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_SEND_CNAP, voidToParcel, parcelToInts, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_SET_CLIP, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(1)},
{RIL_REQUEST_REMOVE_CB_MESSAGE, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_ADD_IMS_CONFERENCE_CALL_MEMBER, stringsToParcel, parcelToInts, COMMAND_SUPPORETD(1)},
{RIL_REQUEST_REMOVE_IMS_CONFERENCE_CALL_MEMBER, stringsToParcel, parcelToInts, COMMAND_SUPPORETD(1)},
{RIL_REQUEST_DIAL_WITH_SIP_URI, stringToParcel, parcelToVoid, COMMAND_SUPPORETD(1)},
{RIL_REQUEST_RESUME_CALL, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(1)},
{RIL_REQUEST_SET_REMOVE_RESTRICT_EUTRAN_MODE, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_VT_DIAL, dialToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_VOICE_ACCEPT, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_REPLACE_VT_CALL, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_CONFERENCE_DIAL, stringsToParcel, parcelToVoid, COMMAND_SUPPORETD(1)},
{RIL_REQUEST_HOLD_CALL, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(1)},
/// @}

//Todo{RIL_REQUEST_AT_COMMAND_WITH_PROXY, rawToParcel, parcelToRaw, COMMAND_SUPPORETD(1)},
/// M: ViLTE. @{
{RIL_REQUEST_VIDEO_CALL_ACCEPT, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
/// @}

/// M: USSI RIL request commands @{
{RIL_REQUEST_SEND_USSI, stringsToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_CANCEL_USSI, voidToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
/// @}

/// M: set Ims capability to MD @{
{RIL_REQUEST_SET_VOLTE_ENABLE, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_SET_WFC_ENABLE, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_REQUEST_SET_IMS_VIDEO_ENABLE, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
/// @}
/// M: ViLTE. @{
{RIL_REQUEST_VT_DIAL_WITH_SIP_URI, stringToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
/// @}
/// M: IMS Deregistration request. @{
{RIL_REQUEST_IMS_DEREG_NOTIFICATION, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
/// @}
{RIL_REQUEST_SET_IMSCFG, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(1)},
{RIL_REQUEST_SWITCH_MODE_FOR_ECC, intsToParcel, NULL, COMMAND_SUPPORETD(0)},

// M: VzW
//{RIL_REQUEST_SYNC_APN_TABLE, stringsToParcel, parcelToVoid, COMMAND_SUPPORETD(0)},
// M: VzW
{RIL_REQUEST_SYNC_DATA_SETTINGS_TO_MD, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(1)},
//Todo{RIL_REQUEST_START_KEEPALIVE_PRO, requestKeepaliveToParcel, parcelToInts, COMMAND_SUPPORETD(1)},
//Todo{RIL_REQUEST_STOP_KEEPALIVE_PRO, intsToParcel, parcelToVoid, COMMAND_SUPPORETD(1)},
