// SPDX-License-Identifier: MediaTekProprietary
/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

    {0, NULL, NULL},  //none
    {RIL_REQUEST_GET_SIM_STATUS, tranferRequestRaw, transferResponseSimStatus},
    {RIL_REQUEST_ENTER_SIM_PIN, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_ENTER_SIM_PUK, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_ENTER_SIM_PIN2, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_ENTER_SIM_PUK2, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_CHANGE_SIM_PIN, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_CHANGE_SIM_PIN2, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_ENTER_NETWORK_DEPERSONALIZATION, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_GET_CURRENT_CALLS, tranferRequestRaw, tranferResponseGetCurrentCalls},
    {RIL_REQUEST_DIAL, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_GET_IMSI, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_HANGUP, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_HANGUP_WAITING_OR_BACKGROUND, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_HANGUP_FOREGROUND_RESUME_BACKGROUND, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SWITCH_WAITING_OR_HOLDING_AND_ACTIVE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_CONFERENCE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_UDUB, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_LAST_CALL_FAIL_CAUSE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SIGNAL_STRENGTH, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_VOICE_REGISTRATION_STATE, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_DATA_REGISTRATION_STATE, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_OPERATOR, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_RADIO_POWER, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_DTMF, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SEND_SMS, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SEND_SMS_EXPECT_MORE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SETUP_DATA_CALL, tranferRequestRaw, tranferResponseDataCallList },
    {RIL_REQUEST_SIM_IO, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SEND_USSD, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_CANCEL_USSD, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_GET_CLIR, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_CLIR, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_QUERY_CALL_FORWARD_STATUS, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_CALL_FORWARD, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_QUERY_CALL_WAITING, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_CALL_WAITING, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SMS_ACKNOWLEDGE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_GET_IMEI, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_GET_IMEISV, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_ANSWER,tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_DEACTIVATE_DATA_CALL, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_QUERY_FACILITY_LOCK, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_FACILITY_LOCK, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_CHANGE_BARRING_PASSWORD, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_QUERY_NETWORK_SELECTION_MODE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_NETWORK_SELECTION_AUTOMATIC, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_NETWORK_SELECTION_MANUAL, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_QUERY_AVAILABLE_NETWORKS , tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_DTMF_START, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_DTMF_STOP, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_BASEBAND_VERSION, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SEPARATE_CONNECTION, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_MUTE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_GET_MUTE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_QUERY_CLIP, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_LAST_DATA_CALL_FAIL_CAUSE, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_DATA_CALL_LIST, tranferRequestRaw, tranferResponseDataCallList },
    {RIL_REQUEST_RESET_RADIO, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_OEM_HOOK_RAW, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_OEM_HOOK_STRINGS, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SCREEN_STATE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_SUPP_SVC_NOTIFICATION, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_WRITE_SMS_TO_SIM, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_DELETE_SMS_ON_SIM, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_BAND_MODE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_QUERY_AVAILABLE_BAND_MODE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_STK_GET_PROFILE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_STK_SET_PROFILE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_STK_SEND_ENVELOPE_COMMAND, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_STK_SEND_TERMINAL_RESPONSE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_STK_HANDLE_CALL_SETUP_REQUESTED_FROM_SIM, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_EXPLICIT_CALL_TRANSFER, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_PREFERRED_NETWORK_TYPE, tranferRequestSetPreferredNetworkType, tranferResponseRaw },
    {RIL_REQUEST_GET_PREFERRED_NETWORK_TYPE, tranferRequestRaw, tranferResponseGetPreferredNetworkType },
    {RIL_REQUEST_GET_NEIGHBORING_CELL_IDS, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_SET_LOCATION_UPDATES, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_CDMA_SET_SUBSCRIPTION_SOURCE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_CDMA_SET_ROAMING_PREFERENCE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_CDMA_QUERY_ROAMING_PREFERENCE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_TTY_MODE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_QUERY_TTY_MODE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_CDMA_SET_PREFERRED_VOICE_PRIVACY_MODE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_CDMA_QUERY_PREFERRED_VOICE_PRIVACY_MODE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_CDMA_FLASH, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_CDMA_BURST_DTMF, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_CDMA_VALIDATE_AND_WRITE_AKEY, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_CDMA_SEND_SMS, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_CDMA_SMS_ACKNOWLEDGE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_GSM_GET_BROADCAST_SMS_CONFIG, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_GSM_SET_BROADCAST_SMS_CONFIG, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_GSM_SMS_BROADCAST_ACTIVATION, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_CDMA_GET_BROADCAST_SMS_CONFIG, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_CDMA_SET_BROADCAST_SMS_CONFIG, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_CDMA_SMS_BROADCAST_ACTIVATION, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_CDMA_SUBSCRIPTION, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_CDMA_WRITE_SMS_TO_RUIM, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_CDMA_DELETE_SMS_ON_RUIM, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_DEVICE_IDENTITY, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_EXIT_EMERGENCY_CALLBACK_MODE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_GET_SMSC_ADDRESS, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_SMSC_ADDRESS, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_REPORT_SMS_MEMORY_STATUS, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_REPORT_STK_SERVICE_IS_RUNNING, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_CDMA_GET_SUBSCRIPTION_SOURCE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_ISIM_AUTHENTICATION, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_ACKNOWLEDGE_INCOMING_GSM_SMS_WITH_PDU, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_STK_SEND_ENVELOPE_WITH_STATUS, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_VOICE_RADIO_TECH, tranferRequestRaw, tranferResponseRadioTech},
    {RIL_REQUEST_GET_CELL_INFO_LIST, tranferRequestRaw,tranferResponseRaw},
    {RIL_REQUEST_SET_UNSOL_CELL_INFO_LIST_RATE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_INITIAL_ATTACH_APN, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_IMS_REGISTRATION_STATE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_IMS_SEND_SMS, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SIM_TRANSMIT_APDU_BASIC, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SIM_OPEN_CHANNEL, tranferRequestOpenChannel, tranferResponseRaw },
    {RIL_REQUEST_SIM_CLOSE_CHANNEL, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SIM_TRANSMIT_APDU_CHANNEL, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_NV_READ_ITEM, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_NV_WRITE_ITEM, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_NV_WRITE_CDMA_PRL, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_NV_RESET_CONFIG, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_UICC_SUBSCRIPTION, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_ALLOW_DATA, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_GET_HARDWARE_CONFIG, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_SIM_AUTHENTICATION, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_GET_DC_RT_INFO, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_SET_DC_RT_INFO_RATE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_DATA_PROFILE, tranferRequestSetDataProfile, tranferResponseRaw },
    {RIL_REQUEST_SHUTDOWN, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_GET_RADIO_CAPABILITY, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_RADIO_CAPABILITY, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_START_LCE, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_STOP_LCE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_PULL_LCEDATA, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_GET_ACTIVITY_INFO, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_ALLOWED_CARRIERS, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_GET_ALLOWED_CARRIERS, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_SEND_DEVICE_STATE, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_SET_UNSOLICITED_RESPONSE_FILTER, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_SIM_CARD_POWER, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_SET_CARRIER_INFO_IMSI_ENCRYPTION, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_START_NETWORK_SCAN, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_STOP_NETWORK_SCAN, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_GET_SLOT_STATUS, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_SET_LOGICAL_TO_PHYSICAL_SLOT_MAPPING, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_START_KEEPALIVE, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_STOP_KEEPALIVE, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_SET_SIGNAL_STRENGTH_REPORTING_CRITERIA, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_SET_LINK_CAPACITY_REPORTING_CRITERIA, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_SET_PREFERRED_DATA_MODEM, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_EMERGENCY_DIAL, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_ENABLE_MODEM, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_SET_SYSTEM_SELECTION_CHANNELS, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_GET_PHONE_CAPABILITY, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_SET_NETWORK_SELECTION_MANUAL_WITH_RAN, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_GET_BARRINGINFO, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_ENABLE_UICC_APPLICATIONS, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_ARE_UICC_APPLICATIONS_ENABLED, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_SET_MODEM_CONFIG, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_ENTER_SIM_DEPERSONALIZATION, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_CDMA_SEND_SMS_EXPECT_MORE, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_ALLOCATE_PDU_SESSION_ID, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_RELEASE_PDU_SESSION_ID, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_START_HANDOVER, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_CANCEL_HANDOVER, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_SET_DATA_THROTTLING, tranferRequestRaw, tranferResponseRaw},
    {RIL_REQUEST_SET_ALLOWED_NETWORK_TYPES_BITMAP, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_GET_ALLOWED_NETWORK_TYPES_BITMAP, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_GET_SLICING_CONFIG, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_GET_SIM_PHONEBOOK_RECORDS, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_GET_SIM_PHONEBOOK_CAPACITY, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_UPDATE_SIM_PHONEBOOK_RECORDS, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_NRDC_STATE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_GET_NRDC_STATE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_GET_SYSTEM_SELECTION_CHANNELS, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_ENABLE_VONR, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_IS_VONR_ENABLED, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_USAGE_SETTING, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_GET_USAGE_SETTING, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_IS_N1_MODE_ENABLED, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_N1_MODE_ENABLED, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_SRVCC_CALL_INFO, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_UPDATE_IMS_REGISTRATION_INFO, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_START_IMS_TRAFFIC, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_STOP_IMS_TRAFFIC, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SEND_ANBR_QUERY, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_TRIGGER_EPS_FALLBACK, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_UPDATE_IMS_CALL_STATUS, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_DEVICE_IMEI, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_EMERGENCY_MODE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_TRIGGER_EMERGENCY_NETWORK_SCAN, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_CANCEL_EMERGENCY_NETWORK_SCAN, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_EXIT_EMERGENCY_MODE, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_NULL_CIPHER_AND_INTEGRITY_ENABLED, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_IS_NULL_CIPHER_AND_INTEGRITY_ENABLED, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SIM_CLOSE_CHANNEL_WITH_SESSION, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_IS_CELLULAR_IDENTIFIER_TRANSPARENCY_ENABLED, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_CELLULAR_IDENTIFIER_TRANSPARENCY_ENABLED, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_SET_SECURITY_ALGORITHMS_UPDATED_ENABLED, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_IS_SECURITY_ALGORITHMS_UPDATED_ENABLED, tranferRequestRaw, tranferResponseRaw },
    {RIL_REQUEST_GET_SIMULTANEOUS_CALLING_SUPPORT, tranferRequestRaw, tranferResponseRaw },