// SPDX-License-Identifier: MediaTekProprietary
/*
*  Copyright (C) 2014 MediaTek Inc.
*
*  Modification based on code covered by the below mentioned copyright
*  and/or permission notice(s).
*/


/* //hardware/ril/librilmtk/ril_commands.h
**
** Copyright 2014, The Android Open Source Project
**
** Licensed under the Apache License, Version 2.0 (the "License");
** you may not use this file except in compliance with the License.
** You may obtain a copy of the License at
**
**     http://www.apache.org/licenses/LICENSE-2.0
**
** Unless required by applicable law or agreed to in writing, software
** distributed under the License is distributed on an "AS IS" BASIS,
** WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
** See the License for the specific language governing permissions and
** limitations under the License.
*/
//#if defined(TELE_FWK)
//
//    {RIL_UNSOL_RESPONSE_RADIO_STATE_CHANGED, parcelToVoid,COMMAND_SUPPORETD(1)},
//    {RIL_UNSOL_RESPONSE_CALL_STATE_CHANGED, parcelToVoid,COMMAND_SUPPORETD(1)},
//    {RIL_UNSOL_RESPONSE_VOICE_NETWORK_STATE_CHANGED, parcelToStrings,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_RESPONSE_NEW_SMS, parcelToString,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_RESPONSE_NEW_SMS_STATUS_REPORT, parcelToString,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_RESPONSE_NEW_SMS_ON_SIM, parcelToInts,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_ON_USSD, parcelToStrings,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_ON_USSD_REQUEST, parcelToVoid,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_NITZ_TIME_RECEIVED, parcelToString,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_SIGNAL_STRENGTH, parcelToRilSignalStrength,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_DATA_CALL_LIST_CHANGED, parcelToDataCallList,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_SUPP_SVC_NOTIFICATION, parcelToSsn,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_STK_SESSION_END, parcelToVoid,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_STK_PROACTIVE_COMMAND, parcelToString,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_STK_EVENT_NOTIFY, parcelToString,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_STK_CALL_SETUP, parcelToInts,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_SIM_SMS_STORAGE_FULL, parcelToVoid,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_SIM_REFRESH, parcelToSimRefresh,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_CALL_RING, parcelToCallRing,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_RESPONSE_SIM_STATUS_CHANGED, parcelToVoid,COMMAND_SUPPORETD(1)},
//#if defined(C2K_SUPPORT)
//    {RIL_UNSOL_RESPONSE_CDMA_NEW_SMS, parcelToCdmaSms,COMMAND_SUPPORETD(0)},
//#else
//    {RIL_UNSOL_RESPONSE_CDMA_NEW_SMS, parcelToCdmaSms,COMMAND_SUPPORETD(0)},
//#endif
//    {RIL_UNSOL_RESPONSE_NEW_BROADCAST_SMS, parcelToRaw,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_CDMA_RUIM_SMS_STORAGE_FULL, parcelToVoid,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_RESTRICTED_STATE_CHANGED, parcelToInts,COMMAND_SUPPORETD(1)},
//    {RIL_UNSOL_ENTER_EMERGENCY_CALLBACK_MODE, parcelToVoid,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_CDMA_CALL_WAITING, parcelToCdmaCallWaiting,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_CDMA_OTA_PROVISION_STATUS, parcelToInts,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_CDMA_INFO_REC, parcelToCdmaInformationRecords,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_OEM_HOOK_RAW, parcelToRaw,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_RINGBACK_TONE, parcelToInts,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_RESEND_INCALL_MUTE, parcelToVoid,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_CDMA_SUBSCRIPTION_SOURCE_CHANGED, parcelToInts,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_CDMA_PRL_CHANGED, parcelToInts,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_EXIT_EMERGENCY_CALLBACK_MODE, parcelToVoid,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_RIL_CONNECTED, parcelToInts,COMMAND_SUPPORETD(1)},
//    {RIL_UNSOL_VOICE_RADIO_TECH_CHANGED, parcelToInts,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_CELL_INFO_LIST, parcelToCellInfoList,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_RESPONSE_IMS_NETWORK_STATE_CHANGED, parcelToVoid,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_UICC_SUBSCRIPTION_STATUS_CHANGED, parcelToInts,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_SRVCC_STATE_NOTIFY, parcelToInts,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_HARDWARE_CONFIG_CHANGED, parcelToHardwareConfig,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_DC_RT_INFO_CHANGED, parcelToDcRtInfo,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_RADIO_CAPABILITY, parcelToRadioCapability,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_ON_SS, parcelToSSData,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_STK_CC_ALPHA_NOTIFY, parcelToStrings,COMMAND_SUPPORETD(0)},
//    {RIL_UNSOL_LCEDATA_RECV, parcelToLceData,COMMAND_SUPPORETD(0)},
//#else

    {RIL_UNSOL_RESPONSE_RADIO_STATE_CHANGED, parcelToVoid,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_RESPONSE_CALL_STATE_CHANGED, parcelToVoid,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_RESPONSE_VOICE_NETWORK_STATE_CHANGED, parcelToStrings,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_RESPONSE_NEW_SMS, parcelToString,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_RESPONSE_NEW_SMS_STATUS_REPORT, parcelToString,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_RESPONSE_NEW_SMS_ON_SIM, parcelToInts,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_ON_USSD, parcelToStrings,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_ON_USSD_REQUEST, parcelToVoid,COMMAND_SUPPORETD(0)},
    {RIL_UNSOL_NITZ_TIME_RECEIVED, parcelToString,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_SIGNAL_STRENGTH, parcelToRilSignalStrength,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_DATA_CALL_LIST_CHANGED, parcelToDataCallList,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_SUPP_SVC_NOTIFICATION, parcelToSsn,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_STK_SESSION_END, parcelToVoid,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_STK_PROACTIVE_COMMAND, parcelToString,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_STK_EVENT_NOTIFY, parcelToString,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_STK_CALL_SETUP, parcelToInts,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_SIM_SMS_STORAGE_FULL, parcelToVoid,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_SIM_REFRESH, parcelToSimRefresh,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_CALL_RING, parcelToCallRing,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_RESPONSE_SIM_STATUS_CHANGED, parcelToVoid,COMMAND_SUPPORETD(1)},
#if defined(C2K_SUPPORT)
    {RIL_UNSOL_RESPONSE_CDMA_NEW_SMS, parcelToCdmaSms,COMMAND_SUPPORETD(1)},
#else
    {RIL_UNSOL_RESPONSE_CDMA_NEW_SMS, parcelToCdmaSms,COMMAND_SUPPORETD(0)},
#endif
    {RIL_UNSOL_RESPONSE_NEW_BROADCAST_SMS, parcelToRaw,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_CDMA_RUIM_SMS_STORAGE_FULL, parcelToVoid,COMMAND_SUPPORETD(0)},
    {RIL_UNSOL_RESTRICTED_STATE_CHANGED, parcelToInts,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_ENTER_EMERGENCY_CALLBACK_MODE, parcelToVoid,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_CDMA_CALL_WAITING, parcelToCdmaCallWaiting,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_CDMA_OTA_PROVISION_STATUS, parcelToInts,COMMAND_SUPPORETD(0)},
    {RIL_UNSOL_CDMA_INFO_REC, parcelToCdmaInformationRecords,COMMAND_SUPPORETD(0)},
    {RIL_UNSOL_OEM_HOOK_RAW, parcelToRaw,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_RINGBACK_TONE, parcelToInts,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_RESEND_INCALL_MUTE, parcelToVoid,COMMAND_SUPPORETD(0)},
    {RIL_UNSOL_CDMA_SUBSCRIPTION_SOURCE_CHANGED, parcelToInts,COMMAND_SUPPORETD(0)},
    {RIL_UNSOL_CDMA_PRL_CHANGED, parcelToInts,COMMAND_SUPPORETD(0)},
    {RIL_UNSOL_EXIT_EMERGENCY_CALLBACK_MODE, parcelToVoid,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_RIL_CONNECTED, parcelToInts,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_VOICE_RADIO_TECH_CHANGED, parcelToInts,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_CELL_INFO_LIST, parcelToCellInfoList,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_RESPONSE_IMS_NETWORK_STATE_CHANGED, parcelToVoid,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_UICC_SUBSCRIPTION_STATUS_CHANGED, parcelToInts,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_SRVCC_STATE_NOTIFY, parcelToInts,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_HARDWARE_CONFIG_CHANGED, parcelToHardwareConfig,COMMAND_SUPPORETD(0)},
    {RIL_UNSOL_DC_RT_INFO_CHANGED, parcelToDcRtInfo,COMMAND_SUPPORETD(0)},
    {RIL_UNSOL_RADIO_CAPABILITY, parcelToRadioCapability,COMMAND_SUPPORETD(1)},
    {RIL_UNSOL_ON_SS, parcelToSSData,COMMAND_SUPPORETD(0)},
    {RIL_UNSOL_STK_CC_ALPHA_NOTIFY, parcelToStrings,COMMAND_SUPPORETD(0)},
    {RIL_UNSOL_LCEDATA_RECV, parcelToLceData,COMMAND_SUPPORETD(0)},
//#endif
