// SPDX-License-Identifier: MediaTekProprietary
/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */
{RIL_UNSOL_NETWORK_INFO, tranferUnsolRaw},
{RIL_UNSOL_PHB_READY_NOTIFICATION,tranferUnsolRaw},
{RIL_UNSOL_ME_SMS_STORAGE_FULL, tranferUnsolRaw},
{RIL_UNSOL_SMS_READY_NOTIFICATION, tranferUnsolRaw},     //10 in alps/hardware/ril/include/telephony/ril.h
{RIL_UNSOL_SIM_MISSING,tranferUnsolRaw},
{RIL_UNSOL_ATCI_RESPONSE, tranferUnsolRaw},
{RIL_UNSOL_SIM_RECOVERY,tranferUnsolRaw},
{RIL_UNSOL_VIRTUAL_SIM_ON,tranferUnsolRaw},
{RIL_UNSOL_VIRTUAL_SIM_OFF,tranferUnsolRaw},
{RIL_UNSOL_INVALID_SIM, tranferUnsolRaw},
{RIL_UNSOL_RESPONSE_PS_NETWORK_STATE_CHANGED, tranferUnsolRaw},
{RIL_UNSOL_IMEI_LOCK, tranferUnsolRaw},
{RIL_UNSOL_SIM_PLUG_OUT, tranferUnsolRaw},
{RIL_UNSOL_SIM_PLUG_IN, tranferUnsolRaw},
{RIL_UNSOL_RESPONSE_ETWS_NOTIFICATION, tranferUnsolRaw},
{RIL_UNSOL_RESPONSE_PLMN_CHANGED, tranferUnsolRaw},
{RIL_UNSOL_RESPONSE_REGISTRATION_SUSPENDED, tranferUnsolRaw},
{RIL_UNSOL_FEMTOCELL_INFO, tranferUnsolRaw},
{RIL_UNSOL_STK_SETUP_MENU_RESET, tranferUnsolRaw},
{RIL_UNSOL_ECONF_SRVCC_INDICATION, tranferUnsolRaw},
{RIL_UNSOL_IMS_ENABLE_DONE, tranferUnsolRaw},
{RIL_UNSOL_IMS_DISABLE_DONE, tranferUnsolRaw},
{RIL_UNSOL_IMS_REGISTRATION_INFO, tranferUnsolRaw},
{RIL_UNSOL_DEDICATE_BEARER_ACTIVATED, tranferUnsolRaw},
{RIL_UNSOL_DEDICATE_BEARER_MODIFIED, tranferUnsolRaw},
{RIL_UNSOL_DEDICATE_BEARER_DEACTIVATED, tranferUnsolRaw},
{RIL_UNSOL_ECONF_RESULT_INDICATION, tranferUnsolRaw},
//Remote SIM ME lock related APIs [Start]
{RIL_UNSOL_MELOCK_NOTIFICATION,tranferUnsolRaw},
//Remote SIM ME lock related APIs [End]
{RIL_UNSOL_CALL_FORWARDING, tranferUnsolRaw},
{RIL_UNSOL_CRSS_NOTIFICATION,tranferUnsolRaw},
{RIL_UNSOL_INCOMING_CALL_INDICATION, tranferUnsolRaw},
{RIL_UNSOL_CIPHER_INDICATION, tranferUnsolRaw},
{RIL_UNSOL_SIM_COMMON_SLOT_NO_CHANGED, tranferUnsolRaw},
{RIL_UNSOL_DATA_ALLOWED, tranferUnsolRaw},
{RIL_UNSOL_CALL_INFO_INDICATION, tranferUnsolRaw},
{RIL_UNSOL_SPEECH_CODEC_INFO, tranferUnsolRaw},
{RIL_UNSOL_REMOVE_RESTRICT_EUTRAN, tranferUnsolRaw},//CC33
{RIL_UNSOL_SIP_CALL_PROGRESS_INDICATOR, tranferUnsolRaw},
/// M: CC071: Add Customer proprietary-IMS RIL interface. @{
{RIL_UNSOL_EMERGENCY_BEARER_SUPPORT_NOTIFY, tranferUnsolRaw},
/// @}
/// M: [C2K][IR][MD-IRAT] URC for GMSS RAT changed. @{ 62
{RIL_UNSOL_GMSS_RAT_CHANGED, tranferUnsolRaw},
//IMS
{RIL_UNSOL_IMS_ENABLE_START, tranferUnsolRaw},
{RIL_UNSOL_IMS_DISABLE_START, tranferUnsolRaw},
{RIL_UNSOL_IMSI_REFRESH_DONE, tranferUnsolRaw},
{RIL_UNSOL_STK_BIP_PROACTIVE_COMMAND, tranferUnsolRaw},
//WorldMode
{RIL_UNSOL_WORLD_MODE_CHANGED, tranferUnsolRaw},
/// M: for 3G VT only @{
{RIL_UNSOL_VT_STATUS_INFO, tranferUnsolRaw},
/// @}
//External SIM APIs [Start]
{RIL_UNSOL_VSIM_OPERATION_INDICATION, tranferUnsolRaw},
//External SIM APIs [End]
{RIL_UNSOL_TRAY_PLUG_IN, tranferUnsolRaw},
{RIL_UNSOL_CALLMOD_CHANGE_INDICATOR, tranferUnsolRaw},
{RIL_UNSOL_VIDEO_CAPABILITY_INDICATOR, tranferUnsolRaw},
/// M: USSI URC commands @{
{RIL_UNSOL_ON_USSI, tranferUnsolRaw},
/// @}
// Merge C2K only URC
{RIL_UNSOL_CDMA_CALL_ACCEPTED, tranferUnsolRaw},
{RIL_UNSOL_CDMA_PLMN_CHANGED, tranferUnsolRaw},
{RIL_UNSOL_NETWORK_EVENT, tranferUnsolRaw},
{RIL_UNSOL_IMS_DEREG_DONE, tranferUnsolRaw},
{RIL_UNSOL_PCO_STATUS, tranferUnsolRaw},
{RIL_UNSOL_DATA_ATTACH_APN_CHANGED, tranferUnsolRaw},
{RIL_UNSOL_TRIGGER_OTASP, tranferUnsolRaw},
{RIL_UNSOL_TX_POWER, tranferUnsolRaw},
{RIL_UNSOL_RESPONSE_CS_NETWORK_STATE_CHANGED, tranferUnsolRaw},
//{RIL_UNSOL_KEEPALIVE_STATUS_PRO, tranferUnsolRaw},

/* M: eMBMS feature */
//{RIL_UNSOL_EMBMS_CELL_INFO_NOTIFICATION, parcelToEmbmsCellInfoNotify},
//{RIL_UNSOL_EMBMS_COVERAGE_STATE, tranferUnsolRaw},
//{RIL_UNSOL_EMBMS_ACTIVE_SESSION, parcelToEmbmsActiveSessionNotify},
//{RIL_UNSOL_EMBMS_AVAILABLE_SESSION, parcelToEmbmsActiveSessionNotify},
//{RIL_UNSOL_EMBMS_SAI_LIST_NOTIFICATION, parcelToEmbmsSaiNotify},
//{RIL_UNSOL_EMBMS_OOS_NOTIFICATION, parcelToEmbmsOosNotify},
//{RIL_UNSOL_EMBMS_MODEM_EE_NOTIFICATION, parcelToEmbmsModemEeNotify},

//{RIL_UNSOL_RADIO_CAPABILITY_SWITCH_START, tranferUnsolRaw},
//{RIL_UNSOL_EMBMS_SESSION_STATUS, tranferUnsolRaw},
//{RIL_UNSOL_CDMA_CARD_INITIAL_ESN_OR_MEID, tranferUnsolRaw},

