// SPDX-License-Identifier: MediaTekProprietary
/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

//#if defined(TELE_FWK)
//{RIL_UNSOL_NETWORK_INFO, parcelToStrings, COMMAND_SUPPORETD(0)},
//#else
{RIL_UNSOL_NETWORK_INFO, parcelToStrings, COMMAND_SUPPORETD(1)},
//#endif
{RIL_UNSOL_PHB_READY_NOTIFICATION,parcelToInts, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_ME_SMS_STORAGE_FULL, parcelToVoid, COMMAND_SUPPORETD(0)},
//#if defined(TELE_FWK)
//{RIL_UNSOL_SMS_READY_NOTIFICATION, parcelToVoid, COMMAND_SUPPORETD(0)},     //10 in alps/hardware/ril/include/telephony/ril.h
//#else
{RIL_UNSOL_SMS_READY_NOTIFICATION, parcelToVoid, COMMAND_SUPPORETD(1)},     //10 in alps/hardware/ril/include/telephony/ril.h
//#endif
{RIL_UNSOL_SIM_MISSING,parcelToInts, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_ATCI_RESPONSE, parcelToString, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_SIM_RECOVERY,parcelToInts, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_VIRTUAL_SIM_ON,parcelToInts, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_VIRTUAL_SIM_OFF,parcelToInts, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_INVALID_SIM, parcelToStrings, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_RESPONSE_PS_NETWORK_STATE_CHANGED, parcelToInts, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_IMEI_LOCK, parcelToVoid, COMMAND_SUPPORETD(0)},
//#if defined(TELE_FWK)
//{RIL_UNSOL_SIM_PLUG_OUT, parcelToVoid, COMMAND_SUPPORETD(0)},
//{RIL_UNSOL_SIM_PLUG_IN, parcelToVoid, COMMAND_SUPPORETD(0)},
//#else
{RIL_UNSOL_SIM_PLUG_OUT, parcelToVoid, COMMAND_SUPPORETD(1)},
{RIL_UNSOL_SIM_PLUG_IN, parcelToVoid, COMMAND_SUPPORETD(1)},
//#endif
{RIL_UNSOL_RESPONSE_ETWS_NOTIFICATION, parcelToEtwsNotification, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_RESPONSE_PLMN_CHANGED, parcelToStrings, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_RESPONSE_REGISTRATION_SUSPENDED, parcelToInts, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_FEMTOCELL_INFO, parcelToStrings, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_STK_SETUP_MENU_RESET, parcelToVoid, COMMAND_SUPPORETD(0)},
//#if defined(TELE_FWK)
//{RIL_UNSOL_ECONF_SRVCC_INDICATION, parcelToInts, COMMAND_SUPPORETD(0)},
//#else
{RIL_UNSOL_ECONF_SRVCC_INDICATION, parcelToInts, COMMAND_SUPPORETD(1)},
//#endif
{RIL_UNSOL_IMS_ENABLE_DONE, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_IMS_DISABLE_DONE, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_IMS_REGISTRATION_INFO, parcelToInts, COMMAND_SUPPORETD(0)},
//#if defined(TELE_FWK)
//{RIL_UNSOL_ECONF_RESULT_INDICATION, parcelToStrings, COMMAND_SUPPORETD(0)},
//#else
{RIL_UNSOL_ECONF_RESULT_INDICATION, parcelToStrings, COMMAND_SUPPORETD(1)},
//#endif
//Remote SIM ME lock related APIs [Start]
{RIL_UNSOL_MELOCK_NOTIFICATION,parcelToInts, COMMAND_SUPPORETD(0)},
//Remote SIM ME lock related APIs [End]
{RIL_UNSOL_CALL_FORWARDING, parcelToInts, COMMAND_SUPPORETD(0)},
//#if defined(TELE_FWK)
//{RIL_UNSOL_CRSS_NOTIFICATION,parcelToCrssN, COMMAND_SUPPORETD(0)},
//{RIL_UNSOL_INCOMING_CALL_INDICATION, parcelToStrings, COMMAND_SUPPORETD(0)},
//#else
{RIL_UNSOL_CRSS_NOTIFICATION,parcelToCrssN, COMMAND_SUPPORETD(1)},
{RIL_UNSOL_INCOMING_CALL_INDICATION, parcelToStrings, COMMAND_SUPPORETD(1)},
//#endif

{RIL_UNSOL_CIPHER_INDICATION, parcelToStrings, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_SIM_COMMON_SLOT_NO_CHANGED, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_DATA_ALLOWED, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_CALL_INFO_INDICATION, parcelToStrings, COMMAND_SUPPORETD(1)},
{RIL_UNSOL_SPEECH_CODEC_INFO, parcelToInts, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_REMOVE_RESTRICT_EUTRAN, parcelToVoid, COMMAND_SUPPORETD(0)},//CC33
{RIL_UNSOL_SIP_CALL_PROGRESS_INDICATOR, parcelToInts, COMMAND_SUPPORETD(0)},
/// M: CC071: Add Customer proprietary-IMS RIL interface. @{
{RIL_UNSOL_EMERGENCY_BEARER_SUPPORT_NOTIFY, parcelToInts, COMMAND_SUPPORETD(0)},
/// @}
/// M: [C2K][IR][MD-IRAT] URC for GMSS RAT changed. @{ 62
{RIL_UNSOL_GMSS_RAT_CHANGED, parcelToInts, COMMAND_SUPPORETD(0)},
/// M: [C2K][IR][MD-IRAT] URC for GMSS RAT changed. @}
//IMS
{RIL_UNSOL_IMS_ENABLE_START, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_IMS_DISABLE_START, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_IMSI_REFRESH_DONE, parcelToVoid, COMMAND_SUPPORETD(0)},
//#if defined(TELE_FWK)
//{RIL_UNSOL_STK_BIP_PROACTIVE_COMMAND, parcelToString, COMMAND_SUPPORETD(0)},
//#else
{RIL_UNSOL_STK_BIP_PROACTIVE_COMMAND, parcelToString, COMMAND_SUPPORETD(1)},
//#endif
//WorldMode
{RIL_UNSOL_WORLD_MODE_CHANGED, parcelToInts, COMMAND_SUPPORETD(0)},
/// M: for 3G VT only @{
{RIL_UNSOL_VT_STATUS_INFO, parcelToInts, COMMAND_SUPPORETD(0)},
/// @}
//External SIM APIs [Start]
{RIL_UNSOL_VSIM_OPERATION_INDICATION, parcelToUnused, COMMAND_SUPPORETD(0)},
//External SIM APIs [End]
{RIL_UNSOL_TRAY_PLUG_IN, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_CALLMOD_CHANGE_INDICATOR, parcelToStrings, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_VIDEO_CAPABILITY_INDICATOR, parcelToStrings, COMMAND_SUPPORETD(0)},

/// M: USSI URC commands @{
{RIL_UNSOL_ON_USSI, parcelToStrings, COMMAND_SUPPORETD(0)},
/// @}
// Merge C2K only URC
{RIL_UNSOL_CDMA_CALL_ACCEPTED, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_CDMA_PLMN_CHANGED, parcelToStrings, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_MODULATION_INFO, parcelToInts, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_NETWORK_EVENT, parcelToInts, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_IMS_DEREG_DONE, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_PCO_STATUS, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_DATA_ATTACH_APN_CHANGED, parcelToVoid, COMMAND_SUPPORETD(0)},
{RIL_UNSOL_TRIGGER_OTASP, parcelToVoid, COMMAND_SUPPORETD(0)},
//#if defined(TELE_FWK)
//{RIL_UNSOL_TX_POWER, parcelToInts, COMMAND_SUPPORETD(0)},
//#else
{RIL_UNSOL_TX_POWER, parcelToInts, COMMAND_SUPPORETD(1)},
//{RIL_UNSOL_KEEPALIVE_STATUS_PRO, parcelToInts, COMMAND_SUPPORETD(1)},
//{RIL_UNSOL_TELEPHONY_RESTART, parcelToVoid, COMMAND_SUPPORETD(1)},
//#endif

/* M: eMBMS feature */
//{RIL_UNSOL_EMBMS_CELL_INFO_NOTIFICATION, parcelToEmbmsCellInfoNotify, COMMAND_SUPPORETD(0)},
//{RIL_UNSOL_EMBMS_COVERAGE_STATE, parcelToInts, COMMAND_SUPPORETD(0)},
//{RIL_UNSOL_EMBMS_ACTIVE_SESSION, parcelToEmbmsActiveSessionNotify, COMMAND_SUPPORETD(0)},
//{RIL_UNSOL_EMBMS_AVAILABLE_SESSION, parcelToEmbmsActiveSessionNotify, COMMAND_SUPPORETD(0)},
//{RIL_UNSOL_EMBMS_SAI_LIST_NOTIFICATION, parcelToEmbmsSaiNotify, COMMAND_SUPPORETD(0)},
//{RIL_UNSOL_EMBMS_OOS_NOTIFICATION, parcelToEmbmsOosNotify, COMMAND_SUPPORETD(0)},
//{RIL_UNSOL_EMBMS_MODEM_EE_NOTIFICATION, parcelToEmbmsModemEeNotify, COMMAND_SUPPORETD(0)},

//{RIL_UNSOL_RADIO_CAPABILITY_SWITCH_START, parcelToVoid, COMMAND_SUPPORETD(0)},
//{RIL_UNSOL_EMBMS_SESSION_STATUS, parcelToInts, COMMAND_SUPPORETD(0)},
//{RIL_UNSOL_CDMA_CARD_INITIAL_ESN_OR_MEID, parcelToString, COMMAND_SUPPORETD(0)},
