/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 *
 * MediaTek Inc. (C) 2016. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

#ifndef __RFX_ECALL_MESSAGE_ID_HEADER__
#define __RFX_ECALL_MESSAGE_ID_HEADER__

// ECall
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ECALL_SET_IVS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ECALL_SET_TEST_NUM)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ECALL_SET_RECONF_NUM)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ECALL_SET_MSD)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ECALL_SET_PSAP)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ECALL_MAKE_ECALL)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ECALL_IVS_PUSH_MSD)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ECALL_PSAP_PULL_MSD)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ECALL_SET_MSD_MODE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ECALL_FAST_MAKE_ECALL)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ECALL_CTRL_SEQUENCE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ECALL_RESET_IVS)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ECALL_SET_PRI)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ECALL_QUERY_ECALL_NUM)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ECALL_SET_NAD_DEREGISTRATION_TIME)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ECALL_SET_REGISTRATION_STATE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ECALL_GET_SIM_INFO)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ECALL_SET_OPRT_MODE)
RFX_MSG_ID_EXPN(RFX_MSG_REQUEST_ECALL_GET_OPRT_MODE)

RFX_MSG_ID_EXPN(RFX_MSG_URC_ECALL_MSDHACK)
RFX_MSG_ID_EXPN(RFX_MSG_URC_ECALL_INDICATIONS)

#endif
