/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2018. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */


{ RFX_STATUS_KEY_CONFIG_DEVICE_VOLTE_AVAILABLE, "1"},
{ RFX_STATUS_KEY_CONFIG_DEVICE_VT_AVAILABLE, "0"},
{ RFX_STATUS_KEY_CONFIG_DEVICE_WFC_AVAILABLE, "0"},
{ RFX_STATUS_KEY_SBP_ID, "12"},
{ RFX_STATUS_KEY_IMS_CONFIG_VOCODER_AMRMODESET, "7"},
{ RFX_STATUS_KEY_IMS_CONFIG_VOCODER_AMRWBMODESET, "2"},
{ RFX_STATUS_KEY_IMS_CONFIG_SIP_SESSION_TIMER, "300"},
{ RFX_STATUS_KEY_IMS_CONFIG_MIN_SE, "300"},
{ RFX_STATUS_KEY_IMS_CONFIG_CANCELLATION_TIMER, "6"},
{ RFX_STATUS_KEY_IMS_CONFIG_TDELAY, "5"},
{ RFX_STATUS_KEY_IMS_CONFIG_SILENT_REDIAL_ENABLE, "1"},
{ RFX_STATUS_KEY_IMS_CONFIG_SIP_T1_TIMER, "3"},
{ RFX_STATUS_KEY_IMS_CONFIG_SIP_T2_TIMER, "16"},
{ RFX_STATUS_KEY_IMS_CONFIG_SIP_TF_TIMER, "30"},
{ RFX_STATUS_KEY_IMS_CONFIG_VLT_SETTING_ENABLED,  "0"},
{ RFX_STATUS_KEY_IMS_CONFIG_LVC_SETTING_ENABLED, "1"},
{ RFX_STATUS_KEY_IMS_CONFIG_DOMAIN_NAME, "vzims.com"},
{ RFX_STATUS_KEY_IMS_CONFIG_SMS_FORMAT, "1"},
{ RFX_STATUS_KEY_IMS_CONFIG_SMS_OVER_IP, "1"},
{ RFX_STATUS_KEY_IMS_CONFIG_PUBLISH_TIMER, "1200"},
{ RFX_STATUS_KEY_IMS_CONFIG_PUBLISH_TIMER_EXTENDED, "86400"},
{ RFX_STATUS_KEY_IMS_CONFIG_CAPABILITY_DISCOVERY_ENABLED, "1"},
{ RFX_STATUS_KEY_IMS_CONFIG_CAPABILITIES_CACHE_EXPIRATION, "7776000"},
{ RFX_STATUS_KEY_IMS_CONFIG_AVAILABILITY_CACHE_EXPIRATION, "60"},
{ RFX_STATUS_KEY_IMS_CONFIG_CAPABILITIES_POLL_INTERVAL, "625000"},
{ RFX_STATUS_KEY_IMS_CONFIG_SOURCE_THROTTLE_PUBLISH, "60000"},
{ RFX_STATUS_KEY_IMS_CONFIG_MAX_NUMENTRIES_IN_RCL, "100"},
{ RFX_STATUS_KEY_IMS_CONFIG_CAPAB_POLL_LIST_SUB_EXP, "30"},
{ RFX_STATUS_KEY_IMS_CONFIG_GZIP_FLAG, "1"},
{ RFX_STATUS_KEY_IMS_CONFIG_EAB_SETTING_ENABLED, "1"},
{ RFX_STATUS_KEY_IMS_CONFIG_VOICE_OVER_WIFI_ROAMING, "0"},
{ RFX_STATUS_KEY_IMS_CONFIG_VOICE_OVER_WIFI_MODE, "2"},
{ RFX_STATUS_KEY_IMS_CONFIG_PUBLISH_ERROR_RETRY_TIMER, "21600"},
{ RFX_STATUS_KEY_IMS_CONFIG_VOICE_OVER_WIFI_MDN, ""},
{ RFX_STATUS_KEY_PCO_DATA_FEATURE_SUPPORTED, "1"},
