#ifndef __QL_AUDIO_DEFINES_H__
#define __QL_AUDIO_DEFINES_H__

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define QL_AUDIO_STATE_0 (0)
#define QL_AUDIO_STATE_1 (1)

#define QL_AUDIO_PCM_IF_SAMPLE_RATE_8KHZ  (8000)
#define QL_AUDIO_PCM_IF_SAMPLE_RATE_16KHZ (16000)

#define  QL_AUDIO_PLAYBACK_NONBLOCK  (0)
#define  QL_AUDIO_PLAYBACK_BLOCK     (1)

#define QL_AUDIO_FORMAT_PCM_S16_LE (2)
#define QL_AUDIO_FORMAT_PCM_S24_LE (3)
#define QL_AUDIO_FORMAT_PCM_S32_LE (4)

typedef uint64_t ql_audio_handle_t;

#define QL_AUDIO_INVALID_HANDLE ((ql_audio_handle_t)(void *)NULL)

typedef struct ql_audio_tone_config_struct
{
    int32_t low_fre;
    int32_t high_fre;
    int32_t on_duration;
    int32_t off_duration;
    int32_t volume;
    int32_t count;
}ql_audio_tone_config_t;

typedef struct ql_audio_pcm_config_struct
{
    uint32_t period_size;  // Not support 
    uint32_t period_count; // Not support 
    uint32_t flags; // Not support 
    uint32_t num_channels;
    uint32_t sample_rate;
    uint32_t pcm_format;
} ql_audio_pcm_config_t;

typedef enum QL_AUDIO_FE_PCM_DEV_ENUM
{
    QL_AUDIO_FE_PCM_DEV_MIN = -1,
    QL_AUDIO_FE_PCM_DEV_MULTIMEDIA1 = 0,
    QL_AUDIO_FE_PCM_DEV_MULTIMEDIA2,
    QL_AUDIO_FE_PCM_DEV_MULTIMEDIA3,
    QL_AUDIO_FE_PCM_DEV_VOICE_SERVICE,
    QL_AUDIO_FE_PCM_DEV_MAX
} QL_AUDIO_FE_PCM_DEV_E;

typedef enum QL_AUDIO_BE_DAI_ENUM
{
    QL_AUDIO_BE_DAI_MIN = -1,
    QL_AUDIO_BE_DAI_PLAYBACK_PRI_PCM = 0,
    QL_AUDIO_BE_DAI_PLAYBACK_SEC_PCM,
    QL_AUDIO_BE_DAI_PLAYBACK_PRI_I2S,
    QL_AUDIO_BE_DAI_PLAYBACK_SEC_I2S,
    QL_AUDIO_BE_DAI_PLAYBACK_VOICE_TX,
    QL_AUDIO_BE_DAI_PLAYBACK_AFE,
    QL_AUDIO_BE_DAI_PLAYBACK_BT,
    QL_AUDIO_BE_DAI_PLAYBACK_USB,
    QL_AUDIO_BE_DAI_PLAYBACK_EAVB,
    QL_AUDIO_BE_DAI_CAPTURE_PRI_PCM,
    QL_AUDIO_BE_DAI_CAPTURE_SEC_PCM,
    QL_AUDIO_BE_DAI_CAPTURE_PRI_I2S,
    QL_AUDIO_BE_DAI_CAPTURE_SEC_I2S,
    QL_AUDIO_BE_DAI_CAPTURE_VOICE_UL,
    QL_AUDIO_BE_DAI_CAPTURE_VOICE_DL,
    QL_AUDIO_BE_DAI_CAPTURE_AFE,
    QL_AUDIO_BE_DAI_CAPTURE_BT,
    QL_AUDIO_BE_DAI_CAPTURE_USB,
    QL_AUDIO_BE_DAI_CAPTURE_EAVB,
    QL_AUDIO_BE_DAI_PLAYBACK_TER_PCM,
    QL_AUDIO_BE_DAI_PLAYBACK_TER_I2S,
    QL_AUDIO_BE_DAI_CAPTURE_TER_PCM,
    QL_AUDIO_BE_DAI_CAPTURE_TER_I2S,
    QL_AUDIO_BE_DAI_MAX
}QL_AUDIO_BE_DAI_E;

#define QL_AUDIO_BE_DAI_MASK_PLAYBACK_PRI_PCM       (1 << QL_AUDIO_BE_DAI_PLAYBACK_PRI_PCM)
#define QL_AUDIO_BE_DAI_MASK_PLAYBACK_SEC_PCM       (1 << QL_AUDIO_BE_DAI_PLAYBACK_SEC_PCM)
#define QL_AUDIO_BE_DAI_MASK_PLAYBACK_PRI_I2S       (1 << QL_AUDIO_BE_DAI_PLAYBACK_PRI_I2S)
#define QL_AUDIO_BE_DAI_MASK_PLAYBACK_SEC_I2S       (1 << QL_AUDIO_BE_DAI_PLAYBACK_SEC_I2S)
#define QL_AUDIO_BE_DAI_MASK_PLAYBACK_TER_PCM       (1 << QL_AUDIO_BE_DAI_PLAYBACK_TER_PCM)
#define QL_AUDIO_BE_DAI_MASK_PLAYBACK_TER_I2S       (1 << QL_AUDIO_BE_DAI_PLAYBACK_TER_I2S)
#define QL_AUDIO_BE_DAI_MASK_PLAYBACK_VOICE_TX      (1 << QL_AUDIO_BE_DAI_PLAYBACK_VOICE_TX)
#define QL_AUDIO_BE_DAI_MASK_PLAYBACK_AFE           (1 << QL_AUDIO_BE_DAI_PLAYBACK_AFE)
#define QL_AUDIO_BE_DAI_MASK_PLAYBACK_BT            (1 << QL_AUDIO_BE_DAI_PLAYBACK_BT)
#define QL_AUDIO_BE_DAI_MASK_PLAYBACK_USB           (1 << QL_AUDIO_BE_DAI_PLAYBACK_USB)
#define QL_AUDIO_BE_DAI_MASK_PLAYBACK_EAVB          (1 << QL_AUDIO_BE_DAI_PLAYBACK_EAVB)
#define QL_AUDIO_BE_DAI_MASK_CAPTURE_PRI_PCM        (1 << QL_AUDIO_BE_DAI_CAPTURE_PRI_PCM)
#define QL_AUDIO_BE_DAI_MASK_CAPTURE_SEC_PCM        (1 << QL_AUDIO_BE_DAI_CAPTURE_SEC_PCM)
#define QL_AUDIO_BE_DAI_MASK_CAPTURE_PRI_I2S        (1 << QL_AUDIO_BE_DAI_CAPTURE_PRI_I2S)
#define QL_AUDIO_BE_DAI_MASK_CAPTURE_SEC_I2S        (1 << QL_AUDIO_BE_DAI_CAPTURE_SEC_I2S)
#define QL_AUDIO_BE_DAI_MASK_CAPTURE_TER_PCM        (1 << QL_AUDIO_BE_DAI_CAPTURE_TER_PCM)
#define QL_AUDIO_BE_DAI_MASK_CAPTURE_TER_I2S        (1 << QL_AUDIO_BE_DAI_CAPTURE_TER_I2S)
#define QL_AUDIO_BE_DAI_MASK_CAPTURE_VOICE_UL       (1 << QL_AUDIO_BE_DAI_CAPTURE_VOICE_UL)
#define QL_AUDIO_BE_DAI_MASK_CAPTURE_VOICE_DL       (1 << QL_AUDIO_BE_DAI_CAPTURE_VOICE_DL)
#define QL_AUDIO_BE_DAI_MASK_CAPTURE_AFE            (1 << QL_AUDIO_BE_DAI_CAPTURE_AFE)
#define QL_AUDIO_BE_DAI_MASK_CAPTURE_BT             (1 << QL_AUDIO_BE_DAI_CAPTURE_BT)
#define QL_AUDIO_BE_DAI_MASK_CAPTURE_USB            (1 << QL_AUDIO_BE_DAI_CAPTURE_USB)
#define QL_AUDIO_BE_DAI_MASK_CAPTURE_EAVB           (1 << QL_AUDIO_BE_DAI_CAPTURE_EAVB)

typedef enum  QL_AUDIO_PLAYBACK_STATE_ENUM
{
    QL_AUDIO_PLAYBACK_STATE_CLOSE = 0,
    QL_AUDIO_PLAYBACK_STATE_OPEN,
    QL_AUDIO_PLAYBACK_STATE_PREPARE,
    QL_AUDIO_PLAYBACK_STATE_PLAYING,
    QL_AUDIO_PLAYBACK_STATE_FINISHED,
    QL_AUDIO_PLAYBACK_STATE_PAUSE,
    QL_AUDIO_PLAYBACK_STATE_ERROR,
} QL_AUDIO_PLAYBACK_STATE_E;

typedef enum QL_AUDIO_CAPTURE_STATE_ENUM
{
    QL_AUDIO_CAPTURE_STATE_CLOSE = 0,
    QL_AUDIO_CAPTURE_STATE_OPEN,
    QL_AUDIO_CAPTURE_STATE_PREPARE,
    QL_AUDIO_CAPTURE_STATE_CAPTURING,
    QL_AUDIO_CAPTURE_STATE_FINISHED,
    QL_AUDIO_CAPTURE_STATE_PAUSE,
    QL_AUDIO_CAPTURE_STATE_ERROR,
} QL_AUDIO_CAPTURE_STATE_E;

typedef enum QL_AUDIO_STREAM_FORMAT_ENUM
{
    QL_AUDIO_STREAM_FORMAT_PCM = 1,
    QL_AUDIO_STREAM_FORMAT_MP3,
    QL_AUDIO_STREAM_FORMAT_AMR,
    QL_AUDIO_STREAM_FORMAT_AMRNB,
    QL_AUDIO_STREAM_FORMAT_AMRWB,
}QL_AUDIO_STREAM_FORMAT_E;

typedef enum QL_AUDIO_ACDB_DEV_MODE_ENUM
{
    QL_AUDIO_ACDB_DEV_MODE_MIN = -1,
    QL_AUDIO_ACDB_DEV_MODE_HANDSET = 0,
    QL_AUDIO_ACDB_DEV_MODE_HEADSET,
    QL_AUDIO_ACDB_DEV_MODE_SPEAKER,
    QL_AUDIO_ACDB_DEV_MODE_MAX
}QL_AUDIO_ACDB_DEV_MODE_E;

typedef enum
{
    QL_AUDIO_LOOPBACK_STREAM_MIN = -1,
    QL_AUDIO_LOOPBACK_STREAM_PCM = 0,
    QL_AUDIO_LOOPBACK_STREAM_DPCM_TX,
    QL_AUDIO_LOOPBACK_STREAM_DPCM_RX,
    QL_AUDIO_LOOPBACK_STREAM_MAX
}QL_AUDIO_LOOPBACK_STREAM_TYPE_E;

typedef int (*ql_audio_playback_state_cb_f)(ql_audio_handle_t hdl, void *params, QL_AUDIO_PLAYBACK_STATE_E state);

typedef int (*ql_audio_capture_state_cb_f)(ql_audio_handle_t hdl, void *params, QL_AUDIO_CAPTURE_STATE_E state);

typedef void (*ql_audio_service_error_cb_f)(int error);

#ifdef __cplusplus
}
#endif
#endif

