/*******************************************
 * Copyright (c) 2026，德赛西威汽车电子有限公司
 * All rights reserved
 * 文件名: sv_audio_defines.h
 * 编写者: AutoAgent
 * 编写日期: 2026-03-05
 * 简要描述: 定义sv_audio_defines相关接口、数据结构及功能能力。
 * 修改记录:
 *******************************************/

#ifndef __SV_AUDIO_DEFINES_H__
#define __SV_AUDIO_DEFINES_H__

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define SV_AUDIO_STATE_0 (0)
#define SV_AUDIO_STATE_1 (1)

#define SV_AUDIO_PCM_IF_SAMPLE_RATE_8KHZ  (8000)
#define SV_AUDIO_PCM_IF_SAMPLE_RATE_16KHZ (16000)

#define  SV_AUDIO_PLAYBACK_NONBLOCK  (0)
#define  SV_AUDIO_PLAYBACK_BLOCK     (1)

#define SV_AUDIO_FORMAT_PCM_S16_LE (2)
#define SV_AUDIO_FORMAT_PCM_S24_LE (3)
#define SV_AUDIO_FORMAT_PCM_S32_LE (4)

typedef uint64_t sv_audio_handle_t;

#define SV_AUDIO_INVALID_HANDLE ((sv_audio_handle_t)(void *)NULL)

typedef struct sv_audio_tone_config_struct
{
    int32_t low_fre;
    int32_t high_fre;
    int32_t on_duration;
    int32_t off_duration;
    int32_t volume;
    int32_t count;
}sv_audio_tone_config_t;

typedef struct sv_audio_pcm_config_struct
{
    uint32_t period_size;  // Not support 
    uint32_t period_count; // Not support 
    uint32_t flags; // Not support 
    uint32_t num_channels;
    uint32_t sample_rate;
    uint32_t pcm_format;
} sv_audio_pcm_config_t;

typedef enum SV_AUDIO_FE_PCM_DEV_ENUM
{
    SV_AUDIO_FE_PCM_DEV_MIN = -1,
    SV_AUDIO_FE_PCM_DEV_MULTIMEDIA1 = 0,
    SV_AUDIO_FE_PCM_DEV_MULTIMEDIA2,
    SV_AUDIO_FE_PCM_DEV_MULTIMEDIA3,
    SV_AUDIO_FE_PCM_DEV_VOICE_SERVICE,
    SV_AUDIO_FE_PCM_DEV_MAX
} SV_AUDIO_FE_PCM_DEV_E;

typedef enum SV_AUDIO_BE_DAI_ENUM
{
    SV_AUDIO_BE_DAI_MIN = -1,
    SV_AUDIO_BE_DAI_PLAYBACK_PRI_PCM = 0,
    SV_AUDIO_BE_DAI_PLAYBACK_SEC_PCM,
    SV_AUDIO_BE_DAI_PLAYBACK_PRI_I2S,
    SV_AUDIO_BE_DAI_PLAYBACK_SEC_I2S,
    SV_AUDIO_BE_DAI_PLAYBACK_VOICE_TX,
    SV_AUDIO_BE_DAI_PLAYBACK_AFE,
    SV_AUDIO_BE_DAI_PLAYBACK_BT,
    SV_AUDIO_BE_DAI_PLAYBACK_USB,
    SV_AUDIO_BE_DAI_PLAYBACK_EAVB,
    SV_AUDIO_BE_DAI_CAPTURE_PRI_PCM,
    SV_AUDIO_BE_DAI_CAPTURE_SEC_PCM,
    SV_AUDIO_BE_DAI_CAPTURE_PRI_I2S,
    SV_AUDIO_BE_DAI_CAPTURE_SEC_I2S,
    SV_AUDIO_BE_DAI_CAPTURE_VOICE_UL,
    SV_AUDIO_BE_DAI_CAPTURE_VOICE_DL,
    SV_AUDIO_BE_DAI_CAPTURE_AFE,
    SV_AUDIO_BE_DAI_CAPTURE_BT,
    SV_AUDIO_BE_DAI_CAPTURE_USB,
    SV_AUDIO_BE_DAI_CAPTURE_EAVB,
    SV_AUDIO_BE_DAI_PLAYBACK_TER_PCM,
    SV_AUDIO_BE_DAI_PLAYBACK_TER_I2S,
    SV_AUDIO_BE_DAI_CAPTURE_TER_PCM,
    SV_AUDIO_BE_DAI_CAPTURE_TER_I2S,
    SV_AUDIO_BE_DAI_MAX
}SV_AUDIO_BE_DAI_E;

#define SV_AUDIO_BE_DAI_MASK_PLAYBACK_PRI_PCM       (1 << SV_AUDIO_BE_DAI_PLAYBACK_PRI_PCM)
#define SV_AUDIO_BE_DAI_MASK_PLAYBACK_SEC_PCM       (1 << SV_AUDIO_BE_DAI_PLAYBACK_SEC_PCM)
#define SV_AUDIO_BE_DAI_MASK_PLAYBACK_PRI_I2S       (1 << SV_AUDIO_BE_DAI_PLAYBACK_PRI_I2S)
#define SV_AUDIO_BE_DAI_MASK_PLAYBACK_SEC_I2S       (1 << SV_AUDIO_BE_DAI_PLAYBACK_SEC_I2S)
#define SV_AUDIO_BE_DAI_MASK_PLAYBACK_TER_PCM       (1 << SV_AUDIO_BE_DAI_PLAYBACK_TER_PCM)
#define SV_AUDIO_BE_DAI_MASK_PLAYBACK_TER_I2S       (1 << SV_AUDIO_BE_DAI_PLAYBACK_TER_I2S)
#define SV_AUDIO_BE_DAI_MASK_PLAYBACK_VOICE_TX      (1 << SV_AUDIO_BE_DAI_PLAYBACK_VOICE_TX)
#define SV_AUDIO_BE_DAI_MASK_PLAYBACK_AFE           (1 << SV_AUDIO_BE_DAI_PLAYBACK_AFE)
#define SV_AUDIO_BE_DAI_MASK_PLAYBACK_BT            (1 << SV_AUDIO_BE_DAI_PLAYBACK_BT)
#define SV_AUDIO_BE_DAI_MASK_PLAYBACK_USB           (1 << SV_AUDIO_BE_DAI_PLAYBACK_USB)
#define SV_AUDIO_BE_DAI_MASK_PLAYBACK_EAVB          (1 << SV_AUDIO_BE_DAI_PLAYBACK_EAVB)
#define SV_AUDIO_BE_DAI_MASK_CAPTURE_PRI_PCM        (1 << SV_AUDIO_BE_DAI_CAPTURE_PRI_PCM)
#define SV_AUDIO_BE_DAI_MASK_CAPTURE_SEC_PCM        (1 << SV_AUDIO_BE_DAI_CAPTURE_SEC_PCM)
#define SV_AUDIO_BE_DAI_MASK_CAPTURE_PRI_I2S        (1 << SV_AUDIO_BE_DAI_CAPTURE_PRI_I2S)
#define SV_AUDIO_BE_DAI_MASK_CAPTURE_SEC_I2S        (1 << SV_AUDIO_BE_DAI_CAPTURE_SEC_I2S)
#define SV_AUDIO_BE_DAI_MASK_CAPTURE_TER_PCM        (1 << SV_AUDIO_BE_DAI_CAPTURE_TER_PCM)
#define SV_AUDIO_BE_DAI_MASK_CAPTURE_TER_I2S        (1 << SV_AUDIO_BE_DAI_CAPTURE_TER_I2S)
#define SV_AUDIO_BE_DAI_MASK_CAPTURE_VOICE_UL       (1 << SV_AUDIO_BE_DAI_CAPTURE_VOICE_UL)
#define SV_AUDIO_BE_DAI_MASK_CAPTURE_VOICE_DL       (1 << SV_AUDIO_BE_DAI_CAPTURE_VOICE_DL)
#define SV_AUDIO_BE_DAI_MASK_CAPTURE_AFE            (1 << SV_AUDIO_BE_DAI_CAPTURE_AFE)
#define SV_AUDIO_BE_DAI_MASK_CAPTURE_BT             (1 << SV_AUDIO_BE_DAI_CAPTURE_BT)
#define SV_AUDIO_BE_DAI_MASK_CAPTURE_USB            (1 << SV_AUDIO_BE_DAI_CAPTURE_USB)
#define SV_AUDIO_BE_DAI_MASK_CAPTURE_EAVB           (1 << SV_AUDIO_BE_DAI_CAPTURE_EAVB)

typedef enum  SV_AUDIO_PLAYBACK_STATE_ENUM
{
    SV_AUDIO_PLAYBACK_STATE_CLOSE = 0,
    SV_AUDIO_PLAYBACK_STATE_OPEN,
    SV_AUDIO_PLAYBACK_STATE_PREPARE,
    SV_AUDIO_PLAYBACK_STATE_PLAYING,
    SV_AUDIO_PLAYBACK_STATE_FINISHED,
    SV_AUDIO_PLAYBACK_STATE_PAUSE,
    SV_AUDIO_PLAYBACK_STATE_ERROR,
} SV_AUDIO_PLAYBACK_STATE_E;

typedef enum SV_AUDIO_CAPTURE_STATE_ENUM
{
    SV_AUDIO_CAPTURE_STATE_CLOSE = 0,
    SV_AUDIO_CAPTURE_STATE_OPEN,
    SV_AUDIO_CAPTURE_STATE_PREPARE,
    SV_AUDIO_CAPTURE_STATE_CAPTURING,
    SV_AUDIO_CAPTURE_STATE_FINISHED,
    SV_AUDIO_CAPTURE_STATE_PAUSE,
    SV_AUDIO_CAPTURE_STATE_ERROR,
} SV_AUDIO_CAPTURE_STATE_E;

typedef enum SV_AUDIO_STREAM_FORMAT_ENUM
{
    SV_AUDIO_STREAM_FORMAT_PCM = 1,
    SV_AUDIO_STREAM_FORMAT_MP3,
    SV_AUDIO_STREAM_FORMAT_AMR,
    SV_AUDIO_STREAM_FORMAT_AMRNB,
    SV_AUDIO_STREAM_FORMAT_AMRWB,
}SV_AUDIO_STREAM_FORMAT_E;

typedef enum SV_AUDIO_ACDB_DEV_MODE_ENUM
{
    SV_AUDIO_ACDB_DEV_MODE_MIN = -1,
    SV_AUDIO_ACDB_DEV_MODE_HANDSET = 0,
    SV_AUDIO_ACDB_DEV_MODE_HEADSET,
    SV_AUDIO_ACDB_DEV_MODE_SPEAKER,
    SV_AUDIO_ACDB_DEV_MODE_MAX
}SV_AUDIO_ACDB_DEV_MODE_E;

typedef enum
{
    SV_AUDIO_LOOPBACK_STREAM_MIN = -1,
    SV_AUDIO_LOOPBACK_STREAM_PCM = 0,
    SV_AUDIO_LOOPBACK_STREAM_DPCM_TX,
    SV_AUDIO_LOOPBACK_STREAM_DPCM_RX,
    SV_AUDIO_LOOPBACK_STREAM_MAX
}SV_AUDIO_LOOPBACK_STREAM_TYPE_E;

typedef int (*sv_audio_playback_state_cb_f)(sv_audio_handle_t hdl, void *params, SV_AUDIO_PLAYBACK_STATE_E state);

typedef int (*sv_audio_capture_state_cb_f)(sv_audio_handle_t hdl, void *params, SV_AUDIO_CAPTURE_STATE_E state);

typedef void (*sv_audio_service_error_cb_f)(int error);

#ifdef __cplusplus
}
#endif
#endif

