# SPDX-License-Identifier:MediaTekProprietary
all:
	make -f Makefile.libnvram
	make -f Makefile.libfile_op
	make -f Makefile.nvram_daemon
	make -f Makefile.nvram_test


clean:
	make -f Makefile.libnvram clean
	make -f Makefile.libfile_op clean
	make -f Makefile.nvram_daemon clean
	make -f Makefile.nvram_test clean