# SPDX-License-Identifier:MediaTekProprietary
NAME = libfile_op
SRC := $(NAME)
OBJ := $(NAME)
INCLUDES=-Ilibnvram
LIBS=$(TARGET_LDFLAGS) -L. -lnvram

SOURCES_C := $(wildcard $(SRC)/*.c)
OBJECTS_C := $(patsubst $(SRC)/%.c, $(OBJ)/%.o, $(SOURCES_C))

SOURCES_CPP := $(wildcard $(SRC)/*.cpp)
OBJECTS_CPP := $(patsubst $(SRC)/%.cpp, $(OBJ)/%.o, $(SOURCES_CPP))

SOURCES := $(SOURCES_C) $(SOURCES_CPP)
OBJECTS := $(OBJECTS_C) $(OBJECTS_CPP) 

$(NAME).so: $(OBJECTS)
	$(CC) -shared -fPIC $(INCLUDES) $(LIBS) -o $@ $^    
    
$(OBJ)/%.o: $(SRC)/%.c
	${CC} $(CFLAGS) -fPIC -c $< -o $@ $(INCLUDES)

$(OBJ)/%.o: $(SRC)/%.cpp
	${CXX} $(CXXFLAGS) -fPIC -c $< -o $@ $(INCLUDES)

clean:
	rm -f $(NAME).so	