#!/bin/sh

echo "=== Initial: mtkfusionrild Start ===" > /dev/kmsg

boot_mode=`hexdump -v /proc/device-tree/chosen/atag,boot | awk '{print $6}'`
case $boot_mode in
    0000|000b)
        /usr/bin/mtkfusionrild -l libmtkmipc-ril.so &
        echo "=== Initial: mtkfusionrild normal boot ===" > /dev/kmsg
        ;;
    0001)
        echo "META Mode" > /dev/kmsg
        ;;
esac

echo "=== Initial: mtkfusionrild End ===" > /dev/kmsg



