// SPDX-License-Identifier: MediaTekProprietary
// This source code is generated by UdpGeneratorTool, not recommend to modify it directly
#ifndef __Framework2AgpsInterface_H__
#define __Framework2AgpsInterface_H__

#include "mtk_socket_utils.h"

#ifdef __cplusplus
extern "C" {
#endif

#define FRAMEWORK2AGPS_INTERFACE_PROTOCOL_TYPE 302
#define FRAMEWORK2AGPS_INTERFACE_BUFF_SIZE 40

/**
 * The interface from Framework  to AGPS
 */
typedef enum {
    FRAMEWORK2AGPS_INTERFACE_DNS_QUERY_RESULT = 0,
    FRAMEWORK2AGPS_INTERFACE_DNS_QUERY_RESULT2 = 1,
} Framework2AgpsInterface_message_id;



// Sender
bool Framework2AgpsInterface_DnsQueryResult(mtk_socket_fd* client_fd, bool isSuccess, bool hasIpv4, int ipv4, bool hasIpv6, char ipv6[], int ipv6_size);

bool Framework2AgpsInterface_DnsQueryResult2(mtk_socket_fd* client_fd, bool isSuccess, bool hasIpv4, int ipv4, bool hasIpv6, char ipv6[], int ipv6_size, bool hasNetId, int netId);

// Receiver
typedef struct {
    void (*Framework2AgpsInterface_DnsQueryResult_handler) (bool isSuccess, bool hasIpv4, int ipv4, bool hasIpv6, char ipv6[], int ipv6_size);
    void (*Framework2AgpsInterface_DnsQueryResult2_handler) (bool isSuccess, bool hasIpv4, int ipv4, bool hasIpv6, char ipv6[], int ipv6_size, bool hasNetId, int netId);
} Framework2AgpsInterface_callbacks;

bool Framework2AgpsInterface_receiver_decode(char* _buff, Framework2AgpsInterface_callbacks* callbacks);
bool Framework2AgpsInterface_receiver_read_and_decode(int server_fd, Framework2AgpsInterface_callbacks* callbacks);

#ifdef __cplusplus
}
#endif

#endif

